"""create notifications table

Revision ID: 26879674f95a
Revises: f64800b093c7
Create Date: 2026-07-01 22:18:24.919080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '26879674f95a'
down_revision: Union[str, Sequence[str], None] = 'f64800b093c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Define the enum object
    item_type_enum = sa.Enum('SALLABLE', 'NON_SALLABLE', name='itemtype')
    
    # 2. Force PostgreSQL to physically register the 'itemtype' Enum structure first
    item_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_item_id'), 'notifications', ['item_id'], unique=False)
    op.add_column('bulk_imports', sa.Column('file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('invite_tokens_token_hash_key'), 'invite_tokens', type_='unique')
    op.add_column('items', sa.Column('item_type', sa.Enum('SALLABLE', 'NON_SALLABLE', name='itemtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_type')
    op.create_unique_constraint(op.f('invite_tokens_token_hash_key'), 'invite_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('bulk_imports', 'file_link')
    op.drop_index(op.f('ix_notifications_item_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Clean up the custom PostgreSQL type if migrations are reversed
    sa.Enum(name='itemtype').drop(op.get_bind(), checkfirst=True)
