"""add profile picture to users

Revision ID: 270c17509549
Revises: c2d3e4f5a6b7
Create Date: 2026-07-02 00:51:15.779050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270c17509549'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
