"""add bulk_import

Revision ID: f64800b093c7
Revises: 82011f0691f8
Create Date: 2026-06-30 16:41:55.903222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64800b093c7'
down_revision: Union[str, Sequence[str], None] = '82011f0691f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_imports', sa.Column('file_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_imports', 'file_link')
    # ### end Alembic commands ###
